import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  phone1, //category: Phone | Apple 
  phone2, //category: Phone | Apple 
  phone4, //category: Phone | Apple 
  phone5, //category: Phone | Apple 
  phone6, //category: Phone | Apple  
  phone7, //category: Phone | Samsung 
  phone8, //category: Phone | Samsung 
  phone9, //category: Phone | Samsung 
  phone10, //category: Phone | Apple 
  laptop1, 
  laptop2,
  laptop3,
  laptop4,
  headset1,
  headset2,
  headset3,
  headset4,
  mouse1,
  mouse2,
  mouse3,
  mouse4,
  pdf1,
  // IMPRIMANTE_PANTUM_CP2200DW,
  // IMPRIMANTE_PANTUM_BM5100FDW,
  // IMPRIMANTE_PANTUM_M6609N,
  // IMPRIMANTE_PANTUM_P3300DN,
  // IMPRIMANTE_PANTUM_P3300DW,
  // IMPRIMANTE_PANTUM_P2509W,
  // IMPRIMANTE_PANTUM_BP5100DN,
  // IMPRIMANTE_PANTUM_M6559N,
  // IMPRIMANTE_PANTUM_P2509,
  cam1,
  cam2,
  cam3,
  watch1,
  watch2,
  watch3,
  watch4,
  watch5,
  keyb1,
  keyb2,
  keyb3,
  keyb4,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Profile",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: phone1,
    productName: "Iphone 5",
    price: "52.00",
    color: "Metallic Gray",
    badge: true,
    des: "Experience sleek design and powerful performance with the iPhone 5. Featuring a 4-inch Retina display, an A6 chip for speedy processing, and an 8MP iSight camera for stunning photos, the iPhone 5 is perfect for everyday use. Enjoy seamless connectivity with LTE support and the intuitive iOS interface. Upgrade your mobile experience with this stylish and efficient smartphone.",
    cat: "Phone",
  },
  {
    _id: "202",
    img: phone2,
    productName: "Iphone 8",
    price: "305.00",
    color: "White",
    badge: true,
    des: "Elevate your smartphone experience with the iPhone 8. Featuring a stunning 4.7-inch Retina HD display, an A11 Bionic chip for impressive speed and efficiency, and a 12MP camera for capturing detailed photos and 4K videos, the iPhone 8 combines powerful performance with elegant design. Enjoy wireless charging, advanced augmented reality capabilities, and the intuitive iOS interface in this sleek, durable device. Perfect for those who demand both style and functionality.",
    cat: "Phone",
  },
  {
    _id: "203",
    img: phone4,
    productName: "Iphone 12",
    price: "465.00",
    color: "Black",
    badge: true,
    des: "Experience innovation at its finest with the iPhone 12. Featuring a stunning 6.1-inch Super Retina XDR display, the powerful A14 Bionic chip, and an advanced dual-camera system with Night mode, the iPhone 12 delivers exceptional performance and photographic capabilities. With 5G connectivity for lightning-fast downloads and streaming, Ceramic Shield for enhanced durability, and MagSafe for effortless wireless charging and accessory attachment, the iPhone 12 redefines what a smartphone can achieve. Elevate your mobile experience with this sleek and sophisticated device that sets the standard for excellence.",
    cat: "Phone",
  },
  {
    _id: "204",
    img: phone5,
    productName: "Iphone 14",
    price: "665.00",
    color: "Blue",
    badge: true,
    des: "Experience cutting-edge technology with the iPhone 14. Featuring a 6.1-inch Super Retina XDR display, the powerful A16 Bionic chip, and an advanced dual-camera system with enhanced low-light performance, the iPhone 14 takes your photos and videos to the next level. Enjoy lightning-fast 5G connectivity, all-day battery life, and the durability of Ceramic Shield. With innovative features and a sleek design, the iPhone 14 offers unparalleled performance and style for your everyday needs.",
    cat: "Phone",
  },
  {
    _id: "205",
    img: phone6,
    productName: "Iphone 15",
    price: "831.00",
    color: "Gray",
    badge: true,
    des: "Unleash the extraordinary with the iPhone 15. Boasting a brilliant 6.1-inch Super Retina XDR display, the ultra-efficient A17 Bionic chip, and a cutting-edge triple-camera system with advanced computational photography, the iPhone 15 redefines mobile innovation. Enjoy seamless 5G connectivity, exceptional battery life, and the robust durability of Ceramic Shield. With new design enhancements and the intuitive iOS experience, the iPhone 15 offers unparalleled performance, style, and functionality for your everyday adventures.",
    cat: "Phone",
  },
  {
    _id: "206",
    img: phone7,
    productName: "Samsung S10 5G",
    price: "203.00",
    color: "Pearl White",
    badge: true,
    des: "Experience the future with the Samsung S10 5G, featuring a breathtaking 6.7-inch Dynamic AMOLED display for unparalleled color and clarity. Powered by the lightning-fast Snapdragon 855 processor and revolutionary 5G connectivity, this device ensures you stay ahead with blazing internet speeds and seamless performance. Capture every moment in stunning detail with its versatile quad-camera system, making every shot picture-perfect. Upgrade to the Samsung S10 5G and unlock a world of possibilities.",
    cat: "Phone",
  },
  {
    _id: "207",
    img: phone8,
    productName: "Samsung S21 FE",
    price: "584.00",
    color: "Purple",
    badge: true,
    des: "Experience the best of Samsung with the Galaxy S21 FE. Featuring a vibrant 6.4-inch Dynamic AMOLED 2X display, the powerful Snapdragon 888 processor, and a versatile triple-camera system, the S21 FE delivers stunning visuals and performance. Enjoy smooth, lag-free gaming and streaming with 5G connectivity and a 120Hz refresh rate. With a sleek design, long-lasting battery, and enhanced security features, the Galaxy S21 FE offers premium features at an exceptional value.",
    cat: "Phone",
  },
  {
    _id: "208",
    img: phone9,  
    productName: "Samsung S23",
    price: "912.00",
    color: "Purple",
    badge: true,
    des: "The Samsung S23 features a sleek 6.1-inch Dynamic AMOLED display with a 120Hz refresh rate, providing crisp visuals and fluid interactions. Powered by the latest Snapdragon 8 Gen 2 processor, it offers top-tier performance for gaming, multitasking, and AI-driven applications, while its versatile triple-camera system ensures stunning photos and videos in any setting.",
    cat: "Phone",
  },
  {
    _id: "209",
    img: laptop1,
    productName: "Acer Nitro 5",
    price: "862.00",
    color: "Black",
    badge: true,
    des: "Immerse yourself in the heart of gaming with the Acer Nitro 5, the ultimate weapon for victory. Featuring a razor-sharp 15.6-inch Full HD display with a lightning-fast 144Hz refresh rate, every frame comes to life with unprecedented clarity and fluidity. Powering your conquest is the formidable combination of up to an Intel Core i7 processor and NVIDIA GeForce RTX 30 series graphics, ensuring you dominate the battlefield with unrivaled speed and precision. Stay cool under pressure with Acer's advanced cooling technology, allowing you to unleash your full potential without compromise. Elevate your gaming experience with the Acer Nitro 5 and reign supreme in every game.",
    cat: "Laptop",
  },
  {
    _id: "210",
    img: laptop2,
    productName: "Acer Nitro 16",
    price: "892.00",
    color: "Black",
    badge: true,
    des: "Unleash your gaming prowess with the Acer Nitro 16, a powerhouse designed to fuel your passion for gaming. Dive into the action on its expansive 16-inch display, boasting stunning visuals and smooth gameplay that transport you to the heart of the action. With cutting-edge hardware including up to an Intel Core i9 processor and NVIDIA GeForce RTX 30 series graphics, every frame is delivered with lightning-fast speed and jaw-dropping detail. Stay ahead of the competition with advanced cooling technology that ensures peak performance, even during marathon gaming sessions. Elevate your gaming experience to new heights with the Acer Nitro 16 and conquer every challenge that comes your way. ",
    cat: "Laptop",
  },
  {
    _id: "211",
    img: laptop3,
    productName: "MSI GF65 Thin",
    price: "748.00",
    color: "Black ",
    badge: true,
    des: "Step into the future of gaming with the MSI GF65 Thin, where power meets portability for the ultimate gaming experience on the go. Its sleek and lightweight design belies its formidable performance, driven by up to an Intel Core i7 processor and NVIDIA GeForce RTX graphics. Immerse yourself in every game with its stunning 15.6-inch display, boasting vibrant colors and smooth visuals that bring your favorite titles to life. Whether you're dominating the battlefield or conquering the esports arena, the MSI GF65 Thin is your ticket to gaming greatness, wherever you go.",
    cat: "Laptop",
  },
  {
    _id: "212",
    img: laptop4,
    productName: "MSI GF75",
    price: "681.00",
    color: "Black",
    badge: true,
    des: "Elevate your gaming experience to new heights with the MSI GF75, a sleek powerhouse engineered for victory. Featuring a vibrant 17.3-inch display, immerse yourself in every game with stunning visuals and smooth gameplay. Powered by up to an Intel Core i7 processor and NVIDIA GeForce GTX graphics, conquer the competition with lightning-fast speed and precision. With its slim and lightweight design, the MSI GF75 is the perfect companion for gamers on the move, delivering uncompromising performance wherever your adventures take you. Upgrade to the MSI GF75 and unleash your full gaming potential today.",
    cat: "Laptop",
  },
  {
    _id: "213",
    img: headset1,
    productName: "Airpods Max",
    price: "443.00",
    color: "White",
    badge: true,
    des: "Indulge in pure audio luxury with AirPods Max, the ultimate over-ear headphones from Apple. Crafted with premium materials and meticulously engineered, these headphones deliver unparalleled sound quality, adaptive EQ, and active noise cancellation for a truly immersive listening experience. With a sleek design that balances comfort and style, AirPods Max feature computational audio for precise sound reproduction across all frequencies. Seamlessly integrated with the Apple ecosystem, they offer effortless pairing, Siri voice control, and spatial audio for a cinematic listening experience. Elevate your audio experience to new heights with AirPods Max and immerse yourself in the music like never before.",
    cat: "Headset",
  },
  {
    _id: "214",
    img: headset2,
    productName: "Airpods Pro 2 ",
    price: "253.00",
    color: "White",
    badge: true,
    des: " Experience the next level of audio immersion with AirPods Pro 2, the epitome of wireless earbud technology. Featuring active noise cancellation, transparency mode, and spatial audio, these earbuds deliver a truly immersive listening experience. With an all-new design for improved comfort and fit, plus water and sweat resistance, they're perfect for all-day wear and active lifestyles. With seamless integration with Apple devices and the power of Siri at your command, AirPods Pro 2 redefine what's possible with wireless earbuds. Elevate your audio experience with AirPods Pro 2 and immerse yourself in a world of sound like never before.",
    cat: "Headset",
  },
  {
    _id: "215",
    img: headset3,
    productName: "Monitor II ANC Bluetooth Headphones",
    price: "344.00",
    color: "Black",
    badge: true,
    des: "Experience the pinnacle of audio excellence with the Monitor II ANC Bluetooth Headphones from Marshall. Designed to deliver immersive sound and unrivaled comfort, these headphones feature active noise cancellation technology, allowing you to block out distractions and immerse yourself in your favorite music or podcasts. With up to 30 hours of wireless playtime and custom-tuned drivers, every note is delivered with precision and clarity, while the ergonomic design ensures a comfortable fit for all-day listening. Elevate your audio experience with the Monitor II ANC Bluetooth Headphones and enjoy music the way it was meant to be heard.",
    cat: "Headset",
  },
  {
    _id: "216",
    img: headset4,
    productName: "Marshall Motif II ANC True Wireless Earbuds",
    price: "289.00",
    color: "Black",
    badge: true,
    des: "Experience freedom and superior sound quality with the Marshall Motif II ANC True Wireless Earbuds. Featuring advanced active noise cancellation technology, these earbuds block out external distractions, allowing you to focus on your music with unparalleled clarity. With up to 20 hours of total playtime and customizable EQ settings, enjoy your favorite tracks with rich, immersive sound tailored to your preferences. The sleek and ergonomic design ensures a comfortable fit for all-day wear, while Bluetooth 5.2 connectivity provides seamless pairing and reliable wireless performance. Elevate your listening experience with the Marshall Motif II ANC True Wireless Earbuds and enjoy music on the go like never before.",
    cat: "Headset",
  },
  {
    _id: "217",
    img: mouse1,
    productName: "Logitech G703 Wireless",
    price: "89.00",
    color: "Black",
    badge: true,
    des: "Featuring the advanced HERO 25K gaming sensor for sub-micron tracking and 10x power efficiency over previous generation. Pro-grade LIGHTSPEED wireless delivers ultralow-latency for peak performance.",
    cat: "Mouse",
  },
  {
    _id: "219",
    img: mouse2,
    productName: "Logitech G PRO X Superlight 2",
    price: "159.00",
    color: "Black",
    badge: true,
    des: "LIGHTSPEED Wireless Gaming mouse. The next evolution of our championship-winning mouse. Meet the new weapon of choice for the world’s top esports athletes.",
    cat: "Mouse",
  },
  {
    _id: "220",
    img: mouse3,
    productName: "Razer Naga",
    price: "120.00",
    color: "Gray",
    badge: true,
    des: "With its unique 12-button thumb grid and ergonomic design, the Razer Naga provides MMO gamers the control they need for high-level raiding and PvP. Ideal for medium to large hand sizes and users who favor a palm or claw grip, choose the perfect model that adapts to all your needs.",
    cat: "Mouse",
  },
  {
    _id: "221",
    img: mouse4,
    productName: "Razer Taipan",
    price: "113.00",
    color: "Black",
    badge: true,
    des: "Unleash your gaming potential with the Razer Taipan, a precision-engineered gaming mouse designed for ultimate performance. Featuring an ambidextrous design, customizable buttons, and a 4G dual-sensor system, the Taipan delivers lightning-fast response times and pinpoint accuracy for competitive gaming. With Razer Synapse software, you can personalize your mouse settings and macros to suit your play style, while its ergonomic design ensures comfort during long gaming sessions. Elevate your gaming experience with the Razer Taipan and dominate the competition with unrivaled precision and control.",
    cat: "Mouse",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "201",
    img: phone1,
    productName: "Iphone 5",
    price: "52.00",
    color: "Metallic Gray",
    badge: true,
    brand: "Apple",
    des: "Experience sleek design and powerful performance with the iPhone 5. Featuring a 4-inch Retina display, an A6 chip for speedy processing, and an 8MP iSight camera for stunning photos, the iPhone 5 is perfect for everyday use. Enjoy seamless connectivity with LTE support and the intuitive iOS interface. Upgrade your mobile experience with this stylish and efficient smartphone.",
    cat: "Phone",
    pdf: pdf1,
    ficheTech: [
      { label: "Dimensions ", value: "58.6 X 123.8 X 7.6mm " },
      { label: "Camera ", value: "3264 x 2448 pixels, 1920 x 1080pixels, 30 fps" },
      { label: "CPU ", value: "ARM Apple Cortex-A-7, 1300 MHz, Cores: 2 " },
      { label: "GPU", value: "PowerVR SGX543 MP3, Cores 3" },
      { label: "RAM ", value: "1GB, 533 MHz ",},
      { label: "Storage ", value: "16GB, 32GB, 64GB" },
      { label: "USB ", value: "2.0" },
      { label: "Display  ", value: "4 inch, IPS, 640 x 1136 pixels, 24 bit" },
      { label: "OS ", value: "IOS 6.1.4" },
    ],
  },
  {
    _id: "202",
    img: phone2,
    productName: "Iphone 8",
    price: "305",
    color: "White",
    badge: true,
    brand: "Apple",
    des: "Elevate your smartphone experience with the iPhone 8. Featuring a stunning 4.7-inch Retina HD display, an A11 Bionic chip for impressive speed and efficiency, and a 12MP camera for capturing detailed photos and 4K videos, the iPhone 8 combines powerful performance with elegant design. Enjoy wireless charging, advanced augmented reality capabilities, and the intuitive iOS interface in this sleek, durable device. Perfect for those who demand both style and functionality.",
    cat: "Phone",
    pdf: pdf1,
    ficheTech: [
      { label: "Vitesse d'impression ", value: "40ppm(A4)/42ppm(lettre) " },
      { label: "Temps de sortie de la première page ", value: "≤6.9 s" },

      {
        label: "Nombre de pages mensuel recommandé",
        value: "750 à 4,000 Pages",
      },
      { label: "Résolution d'impression", value: "Max.1,200x1,200 dpi" },
      {
        label: "Langage d'impression ",
        value: "PCL5e, PCL6, PS        ",
      },
      { label: "Vitesse du processeur", value: "1.2 GHz" },
      { label: "Mémoire", value: "512 MB" },
      {
        label: "Panneau de commande ",
        value: "LCD 2 lignes ||  Écran tactile 3,5 pouces      ",
      },
      { label: "Impression recto-verso automatique      ", value: "Oui" },
      {
        label: "Autres fonctions d'impression      ",
        value:
          "Impression brochure, impression sécurisée, impression disque USB Compatible AirPrint, Mopria, APP mobile (APP iOS/App Android)",
      },
      { label: "Vitese de copie ", value: "40ppm(A4)/42ppm(lettre)" },
      {
        label: "Temps de sortie de la première page",
        value: "Plateau : moins de 10 s ADF : moins de 11 s",
      },
    ],
  },

  {
    _id: "203",
    img: phone4,
    productName: "Iphone 12",
    price: "465",
    color: "Black",
    badge: true,
    brand: "Apple",
    des: "Experience innovation at its finest with the iPhone 12. Featuring a stunning 6.1-inch Super Retina XDR display, the powerful A14 Bionic chip, and an advanced dual-camera system with Night mode, the iPhone 12 delivers exceptional performance and photographic capabilities. With 5G connectivity for lightning-fast downloads and streaming, Ceramic Shield for enhanced durability, and MagSafe for effortless wireless charging and accessory attachment, the iPhone 12 redefines what a smartphone can achieve. Elevate your mobile experience with this sleek and sophisticated device that sets the standard for excellence.",
    cat: "Phone",
    pdf: pdf1,
    ficheTech: [
      { label: "Vitesse d'impression ", value: "40ppm(A4)/42ppm(lettre) " },
      { label: "Temps de sortie de la première page ", value: "≤6.9 s" },

      {
        label: "Nombre de pages mensuel recommandé",
        value: "750 à 4,000 Pages",
      },
      { label: "Résolution d'impression", value: "Max.1,200x1,200 dpi" },
      {
        label: "Langage d'impression ",
        value: "PCL5e, PCL6, PS        ",
      },
      { label: "Vitesse du processeur", value: "1.2 GHz" },
      { label: "Mémoire", value: "512 MB" },
      {
        label: "Panneau de commande ",
        value: "LCD 2 lignes ||  Écran tactile 3,5 pouces      ",
      },
      { label: "Impression recto-verso automatique      ", value: "Oui" },
      {
        label: "Autres fonctions d'impression      ",
        value:
          "Impression brochure, impression sécurisée, impression disque USB Compatible AirPrint, Mopria, APP mobile (APP iOS/App Android)",
      },
      { label: "Vitese de copie ", value: "40ppm(A4)/42ppm(lettre)" },
      {
        label: "Temps de sortie de la première page",
        value: "Plateau : moins de 10 s ADF : moins de 11 s",
      },
    ],
  },
  {
    _id: "2005",
    img: phone5,
    productName: "Iphone 14",
    price: "665",
    color: "Blue",
    badge: true,
    brand: "Apple",
    des: "Experience cutting-edge technology with the iPhone 14. Featuring a 6.1-inch Super Retina XDR display, the powerful A16 Bionic chip, and an advanced dual-camera system with enhanced low-light performance, the iPhone 14 takes your photos and videos to the next level. Enjoy lightning-fast 5G connectivity, all-day battery life, and the durability of Ceramic Shield. With innovative features and a sleek design, the iPhone 14 offers unparalleled performance and style for your everyday needs.",
    cat: "Phone",
    pdf: pdf1,
    ficheTech: [
      { label: "gtin	", value: "M6559N      " },
      { label: "Marque	", value: "PANTUM      " },
      { label: "fonctions	", value: "Monofonction      " },
      { label: "Technologie d impression		", value: "Laser      " },
      { label: "Impression	", value: "Noir & Blanc      " },
      { label: "Vitesse du Processeur		", value: "600MHz      " },
      {
        label: "Capacité papier		",
        value: "Capacité standard: 1 600 pages      ",
      },
      { label: "Gestion d entrée Papier Standard		", value: "150 pages      " },
      { label: "Premiére Page Imprimée		", value: "Moins de 7.8s      " },
      { label: "Cycle d utilisation Mensuel		", value: "15 000 pages      " },
      {
        label: "Résolution d impression		",
        value: "Max. 1 200 × 1 200 ppp      ",
      },
      {
        label: "Résolution d'impression Noir		",
        value: "Max. 1 200 × 1 200 ppp      ",
      },
      { label: "formats		", value: "A4      " },
      { label: "Sortie papier		", value: "100 pages      " },
      {
        label: "Vitesse de Copie Noir Blanc		",
        value: "22 ppm (A4) / 23 ppm (Lettre)      ",
      },
      { label: "Poids		", value: "4,75 kg      " },
    ],
  },

  {
    _id: "20005",
    img: phone6,
    productName: "Iphone 15 Pro Max",
    price: "831",
    color: "Gray",
    badge: true,
    brand: "Apple",
    des: "   Unleash the extraordinary with the iPhone 15. Boasting a brilliant 6.1-inch Super Retina XDR display, the ultra-efficient A17 Bionic chip, and a cutting-edge triple-camera system with advanced computational photography, the iPhone 15 redefines mobile innovation. Enjoy seamless 5G connectivity, exceptional battery life, and the robust durability of Ceramic Shield. With new design enhancements and the intuitive iOS experience, the iPhone 15 offers unparalleled performance, style, and functionality for your everyday adventures.",
    cat: "Phone",
    pdf: pdf1,
    ficheTech: [
      { label: "Dimensions ", value: "159.9 x 76.7 x 8.3 mm (6.30 x 3.02 x 0.33 in)" },
      { label: "Camera ", value: "4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 10-bit HDR, Dolby Vision HDR (up to 60fps), ProRes, Cinematic mode (4K@24/30fps), 3D (spatial) video, stereo sound rec." },
      { label: "CPU ", value: "Hexa-core (2x3.78 GHz + 4x2.11 GHz)" },
      { label: "GPU", value: "Apple GPU (6-core graphics)" },
      { label: "RAM ", value: "8GB RAM",},
      { label: "Storage ", value: "256GB, 512GB, 1TB" },
      { label: "Display  ", value: "6.7 inches, 110.2 cm2 (~89.8% screen-to-body ratio)" },
      { label: "OS ", value: "iOS 17, upgradable to iOS 17.5.1" },
    ],
  },

  {
    _id: "206",
    img: phone7,
    productName: "Samsung S10 5G",
    price: "203",
    color: "Pearl White",
    badge: true,
    brand: "Samsung",
    des: "Experience the future of connectivity with the Samsung Galaxy S10 5G, featuring a sleek design and ultra-fast 5G technology. Enjoy a stunning 6.7-inch Dynamic AMOLED display and capture professional-quality photos with the versatile quad-camera system. Stay powered all day with a robust battery and convenient fast wireless charging.",
    cat: "Phone",
    pdf: pdf1,
    ficheTech: [
      { label: "gtin	", value: "P3300DN      " },
      { label: "fonctions	", value: "Monofonction      " },
      { label: "Mémoire	", value: "256MO      " },
      { label: "Technologie d impression		", value: "laser      " },
      { label: "Impression		", value: "Noir & Blanc      " },
      { label: "Connectivite		", value: "Réseau      " },
      { label: "Vitesse du Processeur		", value: "350 MHz      " },
      { label: "Type ecran		", value: "LCD 2 lignes      " },
      {
        label: "Consommation d énergie		",
        value:
          "Impression : 525 W en moyenne Veille : 50 W en veille : moins de 2 W      ",
      },
      {
        label: "Gestion d entrée Papier Standard		",
        value: "Papier Bac d'alimentation: 250pages      ",
      },
      { label: "Premiére Page Imprimée		", value: "Moins de 8,2 secondes      " },
      {
        label: "Vitesse d impression Noir		",
        value: "33 ppm (A4) / 35 ppm (Lettre)      ",
      },
      { label: "Cycle d utilisation Mensuel		", value: "60000pages      " },
      {
        label: "Résolution d impression		",
        value: "1 200 x 1 200 dpi (maximum)      ",
      },
      { label: "formats	", value: "A4      " },
      {
        label: "Connecteurs		",
        value: "USB2.0 haut débit / Ethernet：IEEE 802.3 10/100Base-Tx      ",
      },
      { label: "Fonctionnalités		", value: "Impression      " },
      {
        label: "Volume de Pages Mensuel Recommandé		",
        value: "750 à 3 500 pages      ",
      },
      { label: "Dimensions		", value: "354 x 334 x 232mm      " },
      { label: "Garantie	", value: "1ANS      " },
    ],
  },

  {
    _id: "207",
    img: phone8,
    productName: "Samsung S21 FE",
    price: "584",
    color: "Purple",
    badge: true,
    brand: "Samsung",
    des: "   Experience the best of Samsung with the Galaxy S21 FE. Featuring a vibrant 6.4-inch Dynamic AMOLED 2X display, the powerful Snapdragon 888 processor, and a versatile triple-camera system, the S21 FE delivers stunning visuals and performance. Enjoy smooth, lag-free gaming and streaming with 5G connectivity and a 120Hz refresh rate. With a sleek design, long-lasting battery, and enhanced security features, the Galaxy S21 FE offers premium features at an exceptional value.",
    cat: "Phone",
    pdf: pdf1,
    ficheTech: [
      { label: "gtin		", value: "P3300DW      " },
      { label: "fonctions	", value: "Monofonction      " },
      { label: "Mémoire	", value: "256 Mo      " },
      { label: "Technologie d impression		", value: "Laser      " },
      { label: "Connectivite	", value: "WIFI      " },
      { label: "Vitesse du Processeur		", value: "350 MHz      " },
      { label: "Type ecran		", value: "LCD 2 lignes      " },
      {
        label: "Consommation d énergie		",
        value:
          "Impression : 525 W en moyenne Veille : 50 W en veille : moins de 2 W      ",
      },
      {
        label: "Gestion d entrée Papier Standard		",
        value: "Papier Bac d'alimentation: 250pages      ",
      },
      { label: "Premiére Page Imprimée		", value: "Moins de 8,2 secondes      " },
      {
        label: "Vitesse d impression Noir		",
        value: "33 ppm (A4) / 35 ppm (Lettre)      ",
      },
      { label: "Cycle d utilisation Mensuel		", value: "60000pages      " },
      { label: "Résolution d impression		", value: "Max.1200x1200 dpi      " },
      {
        label: "Volume de Pages Mensuel Recommandé		",
        value: "750 à 3 500 pages      ",
      },
      {
        label: "Interface Réseau	",
        value:
          "Ethernet USB 2.0 haut débit : Wi-Fi IEEE 802.3 10/100Base-Tx : IEEE 802.11b/g/n      ",
      },
      {
        label: "Contenu de L'emballage		",
        value:
          "Imprimante - Cordon d’alimentation - Câble d’interface USB - Plateau de sortie - CD-ROM - Guide de configuration rapide      ",
      },
      { label: "Garantie	", value: "1 ANS      " },
    ],
  },

  {
    _id: "208",
    img: phone9,
    productName: "Samsung S23",
    price: "912",
    color: "Purple",
    badge: true,
    brand: "Samsung",
    des: "  The Samsung S23 features a sleek 6.1-inch Dynamic AMOLED display with a 120Hz refresh rate, providing crisp visuals and fluid interactions. Powered by the latest Snapdragon 8 Gen 2 processor, it offers top-tier performance for gaming, multitasking, and AI-driven applications, while its versatile triple-camera system ensures stunning photos and videos in any setting.",
    cat: "Phone",
    pdf: pdf1,
    ficheTech: [
      { label: "gtin	", value: "P2509W      " },
      { label: "fonctions	", value: "Monofonction      " },
      { label: "Technologie d impression		", value: "Laser      " },
      { label: "Ecran Tactile		", value: "Non      " },
      { label: "Connectivite	", value: "WiFi      " },
      { label: "Vitesse du Processeur		", value: "600MHz      " },
      {
        label: "Capacité papier		",
        value: "Capacité standard: 1 600 pages      ",
      },
      { label: "Premiére Page Imprimée		", value: "Moins de 7.8s      " },
      { label: "Cycle d utilisation Mensuel		", value: "15 000 pages      " },
      {
        label: "Résolution d impression		",
        value: "Max. 1 200 × 1 200 ppp      ",
      },
      { label: "formats	", value: "A4      " },
      { label: "Connecteurs		", value: "USB 2.0, Wi-Fi      " },
      {
        label: "Vitesse de Copie Noir Blanc		",
        value: "22 ppm (A4) / 23 ppm (Lettre)      ",
      },
      {
        label: "Contenu de L'emballage		",
        value:
          "Imprimante - Cordon d’alimentation - Câble d’interface USB - Plateau de sortie - CD-ROM - Guide de configuration rapide      ",
      },
      { label: "Dimensions		", value: "337 x 220 x 178 mm      " },
    ],
  },
  {
    _id: "233",
    img: phone10,
    productName: "Iphone 11",
    price: "431",
    color: "White",
    badge: true,
    brand: "Apple",
    des: "   Discover the power and versatility of the iPhone 11. With its 6.1-inch Liquid Retina display, A13 Bionic chip for lightning-fast performance, and dual-camera system featuring Ultra Wide and Wide lenses, the iPhone 11 lets you capture stunning photos and 4K videos with ease. Enjoy all-day battery life, Face ID for secure authentication, and immersive audio with spatial sound technology. With a sleek design and a wide range of vibrant s to choose from, the iPhone 11 is the perfect companion for your everyday adventures.",
    cat: "Phone",
    pdf: pdf1,
    ficheTech: [],
  },
  {
    _id: "220",
    img: mouse3,
    productName: "Razer Naga",
    price: "120.00",
    color: "Gray",
    badge: true,
    brand: "Razer",
    des: "With its unique 12-button thumb grid and ergonomic design, the Razer Naga provides MMO gamers the control they need for high-level raiding and PvP. Ideal for medium to large hand sizes and users who favor a palm or claw grip, choose the perfect model that adapts to all your needs.",
    cat: "Mouse",
  },
  {
    _id: "221",
    img: mouse4,
    productName: "Razer Taipan",
    price: "113.00",
    color: "Black",
    badge: true,
    brand: "Razer",
    des: "Unleash your gaming potential with the Razer Taipan, a precision-engineered gaming mouse designed for ultimate performance. Featuring an ambidextrous design, customizable buttons, and a 4G dual-sensor system, the Taipan delivers lightning-fast response times and pinpoint accuracy for competitive gaming. With Razer Synapse software, you can personalize your mouse settings and macros to suit your play style, while its ergonomic design ensures comfort during long gaming sessions. Elevate your gaming experience with the Razer Taipan and dominate the competition with unrivaled precision and control.",
    cat: "Mouse",
  },
  {
    _id: "215",
    img: headset3,
    productName: "Marshall II ANC Bluetooth Headphones",
    price: "344.00",
    color: "Black",
    badge: true,
    brand: "Marshall",
    des: "Experience the pinnacle of audio excellence with the Monitor II ANC Bluetooth Headphones from Marshall. Designed to deliver immersive sound and unrivaled comfort, these headphones feature active noise cancellation technology, allowing you to block out distractions and immerse yourself in your favorite music or podcasts. With up to 30 hours of wireless playtime and custom-tuned drivers, every note is delivered with precision and clarity, while the ergonomic design ensures a comfortable fit for all-day listening. Elevate your audio experience with the Monitor II ANC Bluetooth Headphones and enjoy music the way it was meant to be heard.",
    cat: "Headset",
  },
  {
    _id: "216",
    img: headset4,
    productName: "Marshall Motif II ANC True Wireless Earbuds",
    price: "289.00",
    color: "Black",
    badge: true,
    brand: "Marshall",
    des: "Experience freedom and superior sound quality with the Marshall Motif II ANC True Wireless Earbuds. Featuring advanced active noise cancellation technology, these earbuds block out external distractions, allowing you to focus on your music with unparalleled clarity. With up to 20 hours of total playtime and customizable EQ settings, enjoy your favorite tracks with rich, immersive sound tailored to your preferences. The sleek and ergonomic design ensures a comfortable fit for all-day wear, while Bluetooth 5.2 connectivity provides seamless pairing and reliable wireless performance. Elevate your listening experience with the Marshall Motif II ANC True Wireless Earbuds and enjoy music on the go like never before.",
    cat: "Headset",
  },
  {
    _id: "209",
    img: laptop1,
    productName: "Acer Nitro 5",
    price: "862.00",
    color: "Black",
    badge: true,
    brand: "Acer",
    des: "Immerse yourself in the heart of gaming with the Acer Nitro 5, the ultimate weapon for victory. Featuring a razor-sharp 15.6-inch Full HD display with a lightning-fast 144Hz refresh rate, every frame comes to life with unprecedented clarity and fluidity. Powering your conquest is the formidable combination of up to an Intel Core i7 processor and NVIDIA GeForce RTX 30 series graphics, ensuring you dominate the battlefield with unrivaled speed and precision. Stay cool under pressure with Acer's advanced cooling technology, allowing you to unleash your full potential without compromise. Elevate your gaming experience with the Acer Nitro 5 and reign supreme in every game.",
    cat: "Laptop",
  },
  {
    _id: "210",
    img: laptop2,
    productName: "Acer Nitro 16",
    price: "892.00",
    color: "Black",
    badge: true,
    brand: "Acer",
    des: "Unleash your gaming prowess with the Acer Nitro 16, a powerhouse designed to fuel your passion for gaming. Dive into the action on its expansive 16-inch display, boasting stunning visuals and smooth gameplay that transport you to the heart of the action. With cutting-edge hardware including up to an Intel Core i9 processor and NVIDIA GeForce RTX 30 series graphics, every frame is delivered with lightning-fast speed and jaw-dropping detail. Stay ahead of the competition with advanced cooling technology that ensures peak performance, even during marathon gaming sessions. Elevate your gaming experience to new heights with the Acer Nitro 16 and conquer every challenge that comes your way. ",
    cat: "Laptop",
  },

  {
    _id: "211",
    img: laptop3,
    productName: "MSI GF65 Thin",
    price: "748.00",
    color: "Black",
    badge: true,
    brand: "MSI",
    des: "Step into the future of gaming with the MSI GF65 Thin, where power meets portability for the ultimate gaming experience on the go. Its sleek and lightweight design belies its formidable performance, driven by up to an Intel Core i7 processor and NVIDIA GeForce RTX graphics. Immerse yourself in every game with its stunning 15.6-inch display, boasting vibrant colors and smooth visuals that bring your favorite titles to life. Whether you're dominating the battlefield or conquering the esports arena, the MSI GF65 Thin is your ticket to gaming greatness, wherever you go.",
    cat: "Laptop",
  },
  {
    _id: "212",
    img: laptop4,
    productName: "MSI GF75",
    price: "681.00",
    color: "Black",
    badge: true,
    brand: "MSI",
    des: "Elevate your gaming experience to new heights with the MSI GF75, a sleek powerhouse engineered for victory. Featuring a vibrant 17.3-inch display, immerse yourself in every game with stunning visuals and smooth gameplay. Powered by up to an Intel Core i7 processor and NVIDIA GeForce GTX graphics, conquer the competition with lightning-fast speed and precision. With its slim and lightweight design, the MSI GF75 is the perfect companion for gamers on the move, delivering uncompromising performance wherever your adventures take you. Upgrade to the MSI GF75 and unleash your full gaming potential today.",
    cat: "Laptop",
  },
  {
    _id: "213",
    img: headset1,
    productName: "Airpods Max",
    price: "443.00",
    color: "White",
    badge: true,
    brand: "Apple",
    des: "Indulge in pure audio luxury with AirPods Max, the ultimate over-ear headphones from Apple. Crafted with premium materials and meticulously engineered, these headphones deliver unparalleled sound quality, adaptive EQ, and active noise cancellation for a truly immersive listening experience. With a sleek design that balances comfort and style, AirPods Max feature computational audio for precise sound reproduction across all frequencies. Seamlessly integrated with the Apple ecosystem, they offer effortless pairing, Siri voice control, and spatial audio for a cinematic listening experience. Elevate your audio experience to new heights with AirPods Max and immerse yourself in the music like never before.",
    cat: "Headset",
  },
  {
    _id: "214",
    img: headset2,
    productName: "Airpods Pro 2 ",
    price: "253.00",
    color: "White",
    badge: true,
    brand: "Apple",
    des: "Experience the next level of audio immersion with AirPods Pro 2, the epitome of wireless earbud technology. Featuring active noise cancellation, transparency mode, and spatial audio, these earbuds deliver a truly immersive listening experience. With an all-new design for improved comfort and fit, plus water and sweat resistance, they're perfect for all-day wear and active lifestyles. With seamless integration with Apple devices and the power of Siri at your command, AirPods Pro 2 redefine what's possible with wireless earbuds. Elevate your audio experience with AirPods Pro 2 and immerse yourself in a world of sound like never before.",
    cat: "Headset",
  },

  {
    _id: "217",
    img: mouse1,
    productName: "Logitech G703 Wireless",
    price: "89.00",
    color: "Black",
    badge: true,
    brand: "Logitech",
    des: "Featuring the advanced HERO 25K gaming sensor for sub-micron tracking and 10x power efficiency over previous generation. Pro-grade LIGHTSPEED wireless delivers ultralow-latency for peak performance.",
    cat: "Mouse",
  },
  {
    _id: "219",
    img: mouse2,
    productName: "Logitech G PRO X Superlight 2 ",
    price: "159.00",
    color: "Black",
    badge: true,
    brand: "Logitech",
    des: "LIGHTSPEED Wireless Gaming mouse. The next evolution of our championship-winning mouse. Meet the new weapon of choice for the world’s top esports athletes.",
    cat: "Mouse",
  },

  // =================== imprimante hp =================

  {
    _id: "cam1",
    img: cam1,
    productName:
      "Polaroid L-Type Camera",
    price: "119.99",
    color: "White",
    badge: true,
    brand: "Polaroid",
    des: "This lineup of Carrier air conditioner allows you to enjoy the benefits of both style and performance, seamlessly blending with your lifestyle needs. ​",
    cat: "Camera",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "gtin", value: "3YW70A" },
      { label: "Marque", value: "HP" },
      { label: "Destockage", value: "Non" },
      { label: "Ecran", value: "LCD" },
      {
        label: "Taille de L écran cm",
        value: "Affichage LCD 7 segments + icône 5,08 cm (2 pouces)",
      },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Technologie d impression", value: "Jet d'encre" },
      { label: "fonctions", value: "Multifonction" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Impression", value: "Couleur" },
      { label: "formats", value: "A4" },
      { label: "Chargement de Documents", value: "Oui" },
      { label: "Vitesse d impression Noir", value: "Jusqu'à 22 ppm" },
      { label: "Vitesse d impression Couleur", value: "Jusqu'à 16 ppm" },
      { label: "FAX", value: "Non" },
      { label: "Mémoire", value: "256 Mo" },
      {
        label: "Qualité d impression Noir",
        value: "Jusqu'à 1 200 x 1 200 ppp",
      },
      {
        label: "Qualité d impression Couleur",
        value: "Jusqu'à 4 800 x 1 200 ppp",
      },
      { label: "Résolution d impression Couleur", value: "1200x1200dpi" },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Type de Scanner", value: "Scanner à Plat" },
      { label: "Connectivite", value: "USB 2.0, WiFi" },
      { label: "Capacité papier", value: "100 feuilles" },
      { label: "Cycle d utilisation Mensuel", value: "Jusqu'à 1000 pages" },
      {
        label: "Consommation électrique",
        value:
          "0,12 Watts (Arrêt manuel), 3,12 Watts (Prêt), 0,75 Watt (Veille) 5",
      },
      { label: "Grammage", value: "75 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "Imprimante HP Smart Tank 516, Bouteilles d'encre: 3 x HP GT53XL (noir), 3 x HP GT52 (cyan, magenta et jaune), Notice de précaution pour l'encre; Fiche pour le ré-emballage et réglementaire RoH-EAC; Cordon d'alimentation, Guide d'installation; Notice PT",
      },
      { label: "Poids", value: "5,14 kg" },
      { label: "Dimensions", value: "447 x 373 x 158 mm" },
      { label: "Couleur", value: "Noir et Bleu" },
      { label: "Garantie", value: "1 an" },
    ],
  },

  {
    _id: "cam2",
    img: cam2,
    productName: "Nikon D3200",
    price: "980",
    color: "Black",
    badge: true,
    brand: "Nikon",
    des: "The Nikon D3200 is a popular entry-level DSLR camera known for its excellent image quality and user-friendly features. With a 24.2-megapixel sensor, Full HD video recording, and a range of shooting modes, including Guide Mode for beginners, the D3200 offers versatility and ease of use for photographers of all levels. Its compact and lightweight design makes it ideal for travel and everyday photography, while still delivering impressive performance and image clarity.",
    cat: "Camera",
    pdf: pdf1,
    ficheTech: [],
  },

  {
    _id: "cam3",
    img: cam3,
    productName: "Polaroid Land Camera",
    price: "100",
    color: "Black",
    badge: true,
    brand: "Polaroid",
    des: "The Polaroid Land Camera is an iconic instant camera first introduced by Edwin Land in 1948. Its innovative design allowed users to capture and develop photographs within minutes, without the need for external processing. With its foldable bellows and distinctive retro styling, the Land Camera remains a beloved collector's item and symbol of instant photography's golden age.",
    cat: "Camera",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "gtin", value: "Z4B04A" },
      { label: "Marque", value: "HP" },
      { label: "Destockage", value: "Non" },
      { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
      { label: "fonctions", value: "Multifonction" },
      { label: "Impression", value: "Couleur" },
      { label: "Mémoire", value: "Non" },
      { label: "FAX", value: "Non" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Chargement de Documents", value: "Oui" },
      { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
      { label: "Vitesse du Processeur", value: "360 MHz" },
      {
        label: "Impression sans bordure",
        value: "Oui, jusqu’à 210 x 297 mm (A4)",
      },
      { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
      { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
      {
        label: "Résolution d'impression Noir",
        value: "Jusqu'à 1 200 x 1 200 DPI",
      },
      {
        label: "Résolution d impression Couleur",
        value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      {
        label: "Résolution d impression",
        value:
          "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      { label: "Type de Scanner", value: "Scanner à Plat" },
      { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
      { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
      {
        label: "Résolution de numérisation optimisée",
        value: "Jusqu’à 1200 ppp",
      },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Connectivite", value: "USB" },
      { label: "formats", value: "A4" },
      {
        label: "Premiére Page Imprimée",
        value:
          "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
      },
      {
        label: "Alimentation-courant",
        value:
          "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
      },
      {
        label: "Type de Papier pris en charge",
        value:
          "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
      },
      {
        label: "Consommation électrique",
        value:
          "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
      },
      {
        label: "Cycle d utilisation Mensuel",
        value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
      },
      {
        label: "Alimentation papier standard",
        value:
          "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
      },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Type ecran", value: "7 segments et icône LCD" },
      {
        label: "Volume de Pages Mensuel Recommandé",
        value: "400 à 800 (Jusqu'à 1000 pages)",
      },
      { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
      { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
      { label: "Grammage", value: "75 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
      },
      { label: "Poids", value: "4,67 kg" },
      { label: "Couleur", value: "Noir" },
      { label: "Dimensions", value: "525 x 310 x 158 mm" },
      { label: "Garantie", value: "1 an" },
    ],
  },
  // =================== imprimante ricoh =================
  {
    _id: "watch",
    img: watch1,
    productName: "Apple Watch SE",
    price: "36",
    color: "White",
    badge: true,
    brand: "Apple",
    des: "The Apple Watch SE is a more affordable alternative to the flagship Apple Watch series, offering many of the essential features and functionalities at a lower price point. It boasts a sleek design, a vibrant Retina display, and a range of health and fitness tracking capabilities, including heart rate monitoring, activity tracking, and workout metrics. With support for notifications, customizable watch faces, and access to the extensive library of apps available on the watchOS platform, the Apple Watch SE provides a comprehensive smartwatch experience for users seeking both style and functionality.",
    cat: "Watch",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "gtin", value: "Z4B04A" },
      { label: "Marque", value: "HP" },
      { label: "Destockage", value: "Non" },
      { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
      { label: "fonctions", value: "Multifonction" },
      { label: "Impression", value: "Couleur" },
      { label: "Mémoire", value: "Non" },
      { label: "FAX", value: "Non" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Chargement de Documents", value: "Oui" },
      { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
      { label: "Vitesse du Processeur", value: "360 MHz" },
      {
        label: "Impression sans bordure",
        value: "Oui, jusqu’à 210 x 297 mm (A4)",
      },
      { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
      { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
      {
        label: "Résolution d'impression Noir",
        value: "Jusqu'à 1 200 x 1 200 DPI",
      },
      {
        label: "Résolution d impression Couleur",
        value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      {
        label: "Résolution d impression",
        value:
          "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      { label: "Type de Scanner", value: "Scanner à Plat" },
      { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
      { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
      {
        label: "Résolution de numérisation optimisée",
        value: "Jusqu’à 1200 ppp",
      },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Connectivite", value: "USB" },
      { label: "formats", value: "A4" },
      {
        label: "Premiére Page Imprimée",
        value:
          "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
      },
      {
        label: "Alimentation-courant",
        value:
          "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
      },
      {
        label: "Type de Papier pris en charge",
        value:
          "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
      },
      {
        label: "Consommation électrique",
        value:
          "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
      },
      {
        label: "Cycle d utilisation Mensuel",
        value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
      },
      {
        label: "Alimentation papier standard",
        value:
          "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
      },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Type ecran", value: "7 segments et icône LCD" },
      {
        label: "Volume de Pages Mensuel Recommandé",
        value: "400 à 800 (Jusqu'à 1000 pages)",
      },
      { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
      { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
      { label: "Grammage", value: "75 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
      },
      { label: "Poids", value: "4,67 kg" },
      { label: "Couleur", value: "Noir" },
      { label: "Dimensions", value: "525 x 310 x 158 mm" },
      { label: "Garantie", value: "1 an" },
    ],
  },

  {
    _id: "watch2",
    img: watch2,
    productName: "Everton sport watch",
    price: "129",
    color: "Black",
    badge: true,
    brand: "Everton",
    des: "Elevate your active lifestyle with the Etevon Sports Watch. Combining traditional design with modern durability, this watch features a robust stainless steel case and a clear, easy-to-read analog display. Engineered for performance, it offers water resistance and a comfortable, breathable strap, making it perfect for any activity. With precise quartz movement and essential features like a stopwatch and date display, the Etevon Sports Watch seamlessly blends classic style with functionality. Stay on time and in style with a watch that’s built to keep up with your dynamic life.",
    cat: "Watch",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "gtin", value: "Z4B04A" },
      { label: "Marque", value: "HP" },
      { label: "Destockage", value: "Non" },
      { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
      { label: "fonctions", value: "Multifonction" },
      { label: "Impression", value: "Couleur" },
      { label: "Mémoire", value: "Non" },
      { label: "FAX", value: "Non" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Chargement de Documents", value: "Oui" },
      { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
      { label: "Vitesse du Processeur", value: "360 MHz" },
      {
        label: "Impression sans bordure",
        value: "Oui, jusqu’à 210 x 297 mm (A4)",
      },
      { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
      { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
      {
        label: "Résolution d'impression Noir",
        value: "Jusqu'à 1 200 x 1 200 DPI",
      },
      {
        label: "Résolution d impression Couleur",
        value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      {
        label: "Résolution d impression",
        value:
          "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      { label: "Type de Scanner", value: "Scanner à Plat" },
      { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
      { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
      {
        label: "Résolution de numérisation optimisée",
        value: "Jusqu’à 1200 ppp",
      },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Connectivite", value: "USB" },
      { label: "formats", value: "A4" },
      {
        label: "Premiére Page Imprimée",
        value:
          "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
      },
      {
        label: "Alimentation-courant",
        value:
          "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
      },
      {
        label: "Type de Papier pris en charge",
        value:
          "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
      },
      {
        label: "Consommation électrique",
        value:
          "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
      },
      {
        label: "Cycle d utilisation Mensuel",
        value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
      },
      {
        label: "Alimentation papier standard",
        value:
          "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
      },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Type ecran", value: "7 segments et icône LCD" },
      {
        label: "Volume de Pages Mensuel Recommandé",
        value: "400 à 800 (Jusqu'à 1000 pages)",
      },
      { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
      { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
      { label: "Grammage", value: "75 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
      },
      { label: "Poids", value: "4,67 kg" },
      { label: "Couleur", value: "Noir" },
      { label: "Dimensions", value: "525 x 310 x 158 mm" },
      { label: "Garantie", value: "1 an" },
    ],
  },
  {
    _id: "watch3",
    img: watch3,
    productName: "Apple Watch Series 4",
    price: "100",
    color: "White",
    badge: true,
    brand: "Apple",
    des: "Introducing the Apple Watch Series 4, your ultimate health and fitness companion. With a sleek design and advanced features like ECG and fall detection, it keeps you connected and monitors your well-being. Stay active, stay healthy, and stay connected with the Apple Watch Series 4.",
    cat: "Watch",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "gtin", value: "Z4B04A" },
      { label: "Marque", value: "HP" },
      { label: "Destockage", value: "Non" },
      { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
      { label: "fonctions", value: "Multifonction" },
      { label: "Impression", value: "Couleur" },
      { label: "Mémoire", value: "Non" },
      { label: "FAX", value: "Non" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Chargement de Documents", value: "Oui" },
      { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
      { label: "Vitesse du Processeur", value: "360 MHz" },
      {
        label: "Impression sans bordure",
        value: "Oui, jusqu’à 210 x 297 mm (A4)",
      },
      { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
      { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
      {
        label: "Résolution d'impression Noir",
        value: "Jusqu'à 1 200 x 1 200 DPI",
      },
      {
        label: "Résolution d impression Couleur",
        value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      {
        label: "Résolution d impression",
        value:
          "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      { label: "Type de Scanner", value: "Scanner à Plat" },
      { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
      { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
      {
        label: "Résolution de numérisation optimisée",
        value: "Jusqu’à 1200 ppp",
      },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Connectivite", value: "USB" },
      { label: "formats", value: "A4" },
      {
        label: "Premiére Page Imprimée",
        value:
          "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
      },
      {
        label: "Alimentation-courant",
        value:
          "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
      },
      {
        label: "Type de Papier pris en charge",
        value:
          "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
      },
      {
        label: "Consommation électrique",
        value:
          "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
      },
      {
        label: "Cycle d utilisation Mensuel",
        value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
      },
      {
        label: "Alimentation papier standard",
        value:
          "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
      },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Type ecran", value: "7 segments et icône LCD" },
      {
        label: "Volume de Pages Mensuel Recommandé",
        value: "400 à 800 (Jusqu'à 1000 pages)",
      },
      { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
      { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
      { label: "Grammage", value: "75 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
      },
      { label: "Poids", value: "4,67 kg" },
      { label: "Couleur", value: "Noir" },
      { label: "Dimensions", value: "525 x 310 x 158 mm" },
      { label: "Garantie", value: "1 an" },
    ],
  },
  {
    _id: "watch4",
    img: watch4,
    productName: "Everton Mens Velco Watch",
    price: "100",
    color: "Brown Emerald",
    badge: true,
    brand: "Everton",
    des: "Introducing the Everton Mens Velco Watch, your ultimate health and fitness companion. With a sleek design and advanced features like ECG and fall detection, it keeps you connected and monitors your well-being. Stay active, stay healthy, and stay connected with the Everton Mens Velco Watch.",
    cat: "Watch",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "gtin", value: "Z4B04A" },
      { label: "Marque", value: "HP" },
      { label: "Destockage", value: "Non" },
      { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
      { label: "fonctions", value: "Multifonction" },
      { label: "Impression", value: "Couleur" },
      { label: "Mémoire", value: "Non" },
      { label: "FAX", value: "Non" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Chargement de Documents", value: "Oui" },
      { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
      { label: "Vitesse du Processeur", value: "360 MHz" },
      {
        label: "Impression sans bordure",
        value: "Oui, jusqu’à 210 x 297 mm (A4)",
      },
      { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
      { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
      {
        label: "Résolution d'impression Noir",
        value: "Jusqu'à 1 200 x 1 200 DPI",
      },
      {
        label: "Résolution d impression Couleur",
        value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      {
        label: "Résolution d impression",
        value:
          "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      { label: "Type de Scanner", value: "Scanner à Plat" },
      { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
      { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
      {
        label: "Résolution de numérisation optimisée",
        value: "Jusqu’à 1200 ppp",
      },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Connectivite", value: "USB" },
      { label: "formats", value: "A4" },
      {
        label: "Premiére Page Imprimée",
        value:
          "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
      },
      {
        label: "Alimentation-courant",
        value:
          "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
      },
      {
        label: "Type de Papier pris en charge",
        value:
          "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
      },
      {
        label: "Consommation électrique",
        value:
          "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
      },
      {
        label: "Cycle d utilisation Mensuel",
        value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
      },
      {
        label: "Alimentation papier standard",
        value:
          "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
      },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Type ecran", value: "7 segments et icône LCD" },
      {
        label: "Volume de Pages Mensuel Recommandé",
        value: "400 à 800 (Jusqu'à 1000 pages)",
      },
      { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
      { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
      { label: "Grammage", value: "75 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
      },
      { label: "Poids", value: "4,67 kg" },
      { label: "Couleur", value: "Noir" },
      { label: "Dimensions", value: "525 x 310 x 158 mm" },
      { label: "Garantie", value: "1 an" },
    ],
  },
  {
    _id: "watch5",
    img: watch5,
    productName: "Everton Destroyer",
    price: "100",
    color: "Blue",
    badge: true,
    brand: "Everton",
    des: "Introducing the Everton Destroyer, your ultimate health and fitness companion. With a sleek design and advanced features like ECG and fall detection, it keeps you connected and monitors your well-being. Stay active, stay healthy, and stay connected with the Everton Destroyer.",
    cat: "Watch",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "gtin", value: "Z4B04A" },
      { label: "Marque", value: "HP" },
      { label: "Destockage", value: "Non" },
      { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
      { label: "fonctions", value: "Multifonction" },
      { label: "Impression", value: "Couleur" },
      { label: "Mémoire", value: "Non" },
      { label: "FAX", value: "Non" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Chargement de Documents", value: "Oui" },
      { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
      { label: "Vitesse du Processeur", value: "360 MHz" },
      {
        label: "Impression sans bordure",
        value: "Oui, jusqu’à 210 x 297 mm (A4)",
      },
      { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
      { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
      {
        label: "Résolution d'impression Noir",
        value: "Jusqu'à 1 200 x 1 200 DPI",
      },
      {
        label: "Résolution d impression Couleur",
        value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      {
        label: "Résolution d impression",
        value:
          "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      { label: "Type de Scanner", value: "Scanner à Plat" },
      { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
      { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
      {
        label: "Résolution de numérisation optimisée",
        value: "Jusqu’à 1200 ppp",
      },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Connectivite", value: "USB" },
      { label: "formats", value: "A4" },
      {
        label: "Premiére Page Imprimée",
        value:
          "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
      },
      {
        label: "Alimentation-courant",
        value:
          "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
      },
      {
        label: "Type de Papier pris en charge",
        value:
          "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
      },
      {
        label: "Consommation électrique",
        value:
          "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
      },
      {
        label: "Cycle d utilisation Mensuel",
        value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
      },
      {
        label: "Alimentation papier standard",
        value:
          "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
      },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Type ecran", value: "7 segments et icône LCD" },
      {
        label: "Volume de Pages Mensuel Recommandé",
        value: "400 à 800 (Jusqu'à 1000 pages)",
      },
      { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
      { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
      { label: "Grammage", value: "75 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
      },
      { label: "Poids", value: "4,67 kg" },
      { label: "Couleur", value: "Noir" },
      { label: "Dimensions", value: "525 x 310 x 158 mm" },
      { label: "Garantie", value: "1 an" },
    ],
  },

  // =================== imprimante ricoh =================

  {
    _id: "keyb1",
    img: keyb1,
    productName: "logitech keyboard",
    price: "89",
    color: "Black",
    badge: true,
    brand: "Logitech",
    des: "Enhance your typing experience with the Logitech Keyboard. Designed for comfort and efficiency, this keyboard features a sleek, ergonomic design and whisper-quiet keys for a smooth, responsive typing experience. With durable construction and customizable function keys, it’s perfect for both work and play. Enjoy seamless connectivity with options for both wireless and wired use, and experience the reliability that Logitech is known for. Elevate your productivity with a keyboard that combines style, performance, and versatility.",
    cat: "Keyboard",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "gtin", value: "Z4B04A" },
      { label: "Marque", value: "HP" },
      { label: "Destockage", value: "Non" },
      { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
      { label: "fonctions", value: "Multifonction" },
      { label: "Impression", value: "Couleur" },
      { label: "Mémoire", value: "Non" },
      { label: "FAX", value: "Non" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Chargement de Documents", value: "Oui" },
      { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
      { label: "Vitesse du Processeur", value: "360 MHz" },
      {
        label: "Impression sans bordure",
        value: "Oui, jusqu’à 210 x 297 mm (A4)",
      },
      { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
      { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
      {
        label: "Résolution d'impression Noir",
        value: "Jusqu'à 1 200 x 1 200 DPI",
      },
      {
        label: "Résolution d impression Couleur",
        value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      {
        label: "Résolution d impression",
        value:
          "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      { label: "Type de Scanner", value: "Scanner à Plat" },
      { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
      { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
      {
        label: "Résolution de numérisation optimisée",
        value: "Jusqu’à 1200 ppp",
      },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Connectivite", value: "USB" },
      { label: "formats", value: "A4" },
      {
        label: "Premiére Page Imprimée",
        value:
          "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
      },
      {
        label: "Alimentation-courant",
        value:
          "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
      },
      {
        label: "Type de Papier pris en charge",
        value:
          "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
      },
      {
        label: "Consommation électrique",
        value:
          "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
      },
      {
        label: "Cycle d utilisation Mensuel",
        value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
      },
      {
        label: "Alimentation papier standard",
        value:
          "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
      },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Type ecran", value: "7 segments et icône LCD" },
      {
        label: "Volume de Pages Mensuel Recommandé",
        value: "400 à 800 (Jusqu'à 1000 pages)",
      },
      { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
      { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
      { label: "Grammage", value: "75 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
      },
      { label: "Poids", value: "4,67 kg" },
      { label: "Couleur", value: "Noir" },
      { label: "Dimensions", value: "525 x 310 x 158 mm" },
      { label: "Garantie", value: "1 an" },
    ],
  },

  {
    _id: "keyb2",
    img: keyb2,
    productName: "Redragon DAKSA K576R",
    price: "90",
    color: "Black",
    badge: true,
    brand: "Red Dragon",
    des: "Introducing the Redragon DAKSA K576R, the ultimate keyboard for gamers and typists alike. Featuring customizable RGB backlighting and durable mechanical switches, it provides a responsive and tactile typing experience. With its sleek design and programmable keys, the DAKSA K576R offers both style and functionality, ensuring peak performance in every use.",
    cat: "Keyboard",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "gtin", value: "Z4B04A" },
      { label: "Marque", value: "HP" },
      { label: "Destockage", value: "Non" },
      { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
      { label: "fonctions", value: "Multifonction" },
      { label: "Impression", value: "Couleur" },
      { label: "Mémoire", value: "Non" },
      { label: "FAX", value: "Non" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Chargement de Documents", value: "Oui" },
      { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
      { label: "Vitesse du Processeur", value: "360 MHz" },
      {
        label: "Impression sans bordure",
        value: "Oui, jusqu’à 210 x 297 mm (A4)",
      },
      { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
      { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
      {
        label: "Résolution d'impression Noir",
        value: "Jusqu'à 1 200 x 1 200 DPI",
      },
      {
        label: "Résolution d impression Couleur",
        value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      {
        label: "Résolution d impression",
        value:
          "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      { label: "Type de Scanner", value: "Scanner à Plat" },
      { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
      { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
      {
        label: "Résolution de numérisation optimisée",
        value: "Jusqu’à 1200 ppp",
      },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Connectivite", value: "USB" },
      { label: "formats", value: "A4" },
      {
        label: "Premiére Page Imprimée",
        value:
          "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
      },
      {
        label: "Alimentation-courant",
        value:
          "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
      },
      {
        label: "Type de Papier pris en charge",
        value:
          "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
      },
      {
        label: "Consommation électrique",
        value:
          "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
      },
      {
        label: "Cycle d utilisation Mensuel",
        value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
      },
      {
        label: "Alimentation papier standard",
        value:
          "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
      },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Type ecran", value: "7 segments et icône LCD" },
      {
        label: "Volume de Pages Mensuel Recommandé",
        value: "400 à 800 (Jusqu'à 1000 pages)",
      },
      { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
      { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
      { label: "Grammage", value: "75 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
      },
      { label: "Poids", value: "4,67 kg" },
      { label: "Couleur", value: "Noir" },
      { label: "Dimensions", value: "525 x 310 x 158 mm" },
      { label: "Garantie", value: "1 an" },
    ],
  },

  {
    _id: "keyb3",
    img: keyb3,
    productName: "eardbuds",
    price: "1M",
    color: "White",
    badge: true,
    brand: "N/A",
    des: "kang hareld",
    cat: "N/A",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "gtin", value: "Z4B04A" },
      { label: "Marque", value: "HP" },
      { label: "Destockage", value: "Non" },
      { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
      { label: "fonctions", value: "Multifonction" },
      { label: "Impression", value: "Couleur" },
      { label: "Mémoire", value: "Non" },
      { label: "FAX", value: "Non" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Chargement de Documents", value: "Oui" },
      { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
      { label: "Vitesse du Processeur", value: "360 MHz" },
      {
        label: "Impression sans bordure",
        value: "Oui, jusqu’à 210 x 297 mm (A4)",
      },
      { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
      { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
      {
        label: "Résolution d'impression Noir",
        value: "Jusqu'à 1 200 x 1 200 DPI",
      },
      {
        label: "Résolution d impression Couleur",
        value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      {
        label: "Résolution d impression",
        value:
          "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      { label: "Type de Scanner", value: "Scanner à Plat" },
      { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
      { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
      {
        label: "Résolution de numérisation optimisée",
        value: "Jusqu’à 1200 ppp",
      },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Connectivite", value: "USB" },
      { label: "formats", value: "A4" },
      {
        label: "Premiére Page Imprimée",
        value:
          "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
      },
      {
        label: "Alimentation-courant",
        value:
          "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
      },
      {
        label: "Type de Papier pris en charge",
        value:
          "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
      },
      {
        label: "Consommation électrique",
        value:
          "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
      },
      {
        label: "Cycle d utilisation Mensuel",
        value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
      },
      {
        label: "Alimentation papier standard",
        value:
          "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
      },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Type ecran", value: "7 segments et icône LCD" },
      {
        label: "Volume de Pages Mensuel Recommandé",
        value: "400 à 800 (Jusqu'à 1000 pages)",
      },
      { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
      { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
      { label: "Grammage", value: "75 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
      },
      { label: "Poids", value: "4,67 kg" },
      { label: "Couleur", value: "Noir" },
      { label: "Dimensions", value: "525 x 310 x 158 mm" },
      { label: "Garantie", value: "1 an" },
    ],
  },

  {
    _id: "keyb4",
    img: keyb4,
    productName: "harlex",
    price: "1",
    color: "chinoy",
    badge: true,
    brand: "N/A",
    des: "chinito nga gwapo",
    cat: "N/A",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILITÉ", value: "En stock" },
      { label: "gtin", value: "Z4B04A" },
      { label: "Marque", value: "HP" },
      { label: "Destockage", value: "Non" },
      { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
      { label: "fonctions", value: "Multifonction" },
      { label: "Impression", value: "Couleur" },
      { label: "Mémoire", value: "Non" },
      { label: "FAX", value: "Non" },
      { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
      { label: "Chargement de Documents", value: "Oui" },
      { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
      { label: "Vitesse du Processeur", value: "360 MHz" },
      {
        label: "Impression sans bordure",
        value: "Oui, jusqu’à 210 x 297 mm (A4)",
      },
      { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
      { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
      {
        label: "Résolution d'impression Noir",
        value: "Jusqu'à 1 200 x 1 200 DPI",
      },
      {
        label: "Résolution d impression Couleur",
        value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      {
        label: "Résolution d impression",
        value:
          "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
      },
      { label: "Type de Scanner", value: "Scanner à Plat" },
      { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
      { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
      {
        label: "Résolution de numérisation optimisée",
        value: "Jusqu’à 1200 ppp",
      },
      { label: "Recto/Verso", value: "Manuel" },
      { label: "Connectivite", value: "USB" },
      { label: "formats", value: "A4" },
      {
        label: "Premiére Page Imprimée",
        value:
          "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
      },
      {
        label: "Alimentation-courant",
        value:
          "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
      },
      {
        label: "Type de Papier pris en charge",
        value:
          "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
      },
      {
        label: "Consommation électrique",
        value:
          "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
      },
      {
        label: "Cycle d utilisation Mensuel",
        value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
      },
      {
        label: "Alimentation papier standard",
        value:
          "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
      },
      { label: "Ecran Tactile", value: "Non" },
      { label: "Type ecran", value: "7 segments et icône LCD" },
      {
        label: "Volume de Pages Mensuel Recommandé",
        value: "400 à 800 (Jusqu'à 1000 pages)",
      },
      { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
      { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
      { label: "Grammage", value: "75 g/m²" },
      {
        label: "Contenu de L'emballage",
        value:
          "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
      },
      { label: "Poids", value: "4,67 kg" },
      { label: "Couleur", value: "Noir" },
      { label: "Dimensions", value: "525 x 310 x 158 mm" },
      { label: "Garantie", value: "1 an" },
    ],
  },
];
